# Generated by Django 4.2.19 on 2025-02-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_image_alter_product_size_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL of the instagram image', max_length=500)),
                ('link_url', models.URLField(help_text='URL of the instagram post', max_length=500)),
            ],
        ),
    ]
