# Generated by Django 4.2.19 on 2025-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_instagramimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramimage',
            old_name='link_url',
            new_name='post_url',
        ),
        migrations.AlterField(
            model_name='instagramimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the Instagram image', max_length=500, null=True),
        ),
    ]
