# Generated by Django 4.2.19 on 2025-04-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_link_url_instagramimage_post_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='instagramimage',
            name='post_url',
        ),
        migrations.AddField(
            model_name='instagramimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/'),
        ),
        migrations.AddField(
            model_name='instagramimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
